### ISSUE TITLE
Support Redis Sentinel mode

### ISSUE THREAD

**Issue by acheronstyix** [zmartzone/mod_auth_openidc#305] opened 2017-10-17 14:40 UTC
Hello,

Redis is supported as distributed cache mecanism accross several Apache processes/servers.
If I want to set up several Apache servers is to guarantee the service availability. 

Unfortunately, mod_auth_openidc doesn't support Redis with Sentinel mode. Thus, in this configuration, Redis becomes a SPOF.
The main purpose of sentinel is to monitor Redis nodes and gives to Redis clients the right master node to contact. In case of failure, Sentinel nodes elects a new Redis master among Redis nodes.

Sentinel needs to be supported by Redis client libraries. hiredis, used by mod_auth_opendic doesn't support Sentinel. Redis provides a superset of hiredis called hiredis-vip to support cluster mode.

Sentinel : https://redis.io/topics/sentinel 
hiredis-vip : https://github.com/vipshop/hiredis-vip

To support Redis cluster, mod_auth_openidc should implement hiredis-vip and allow users to configure several sentinel nodes in the OIDCRedisCacheServer property.

Thanks
Regards
Aymeric

**Comment by zandbelt** [comment] 2017-10-17 16:19
yeah, but the problem with that would be dependencies/distributions

**Comment by aymeric-lagier** [comment] 2017-10-18 08:56
I don't understand why there's a problem with dependencies/distributions ?

In the current state, to be production ready, the only possible cache type is "file".
- Shared memory can't work with multiple servers
- Memcache doesn't support encryption
- Redis can't be used in cluster mode

File also comes with drawbacks like disk latency.

**Comment by zandbelt** [comment] 2017-10-18 09:00
This works when compiling on a system that has hiredis-vip installed. The problem is that there are no packages in CentOS/Ubuntu/Debian standard repos etc. so who's going to provide and maintain those packages and make sure they end up in those distro's? I've got more than enough work on my plate to do this for mod_auth_openidc itself (see Downloads in https://github.com/pingidentity/mod_auth_openidc/releases).

**Comment by aymeric-lagier** [comment] 2017-10-18 09:21
Yes, I didn't notice hiredis-vip was not available in official repos.
Thank you for your response and good luck :)

**Comment by mimendo** [comment] 2019-02-11 16:16
Hello,
Just a question/suggestion: would it be feasible to statically link hiredis-vip into mod_auth_openidc? It would make the module bigger, but could protect it from possible version incompatibilities.
Kind regards.

**Comment by zandbelt** [comment] 2019-02-11 16:25
I'm not sure that is possible but even if it could, it could conflict with other modules using libhiredis-vip in the future. I'd suggest to keep this an option for custom builds that one can create for oneself. If you need commercial support or this you can contact support@zmartzone.eu

**Comment by kishorsn77** [comment] 2020-10-28 05:15
Hello,
Currently, i am trying to use redis for session caching. when i configure openidc with redis cluster, it doesn't seem to work. 
Is there any plan to support redis cluster going forward? Most of the Enterprise have redis cluster and we do not get standalone redis servers. 
In case if the above isn't possible, then for file based caching, can we use shared location something like a NAS share?

**Comment by zandbelt** [comment] 2020-11-03 14:26
FYI: support for Redis Cluster and Redis Cluster over TLS is now available under a commercial license; please contact sales@zmartzone.eu for inquiries about it

**Comment by rpluem-vf** [comment] 2021-08-18 15:30
Will this Redis Cluster support available under a commercial license be merged into the OSS version and if yes is there any timeline for this?

**Comment by zandbelt** [comment] 2021-08-18 16:39
there are no plans right now to do so

**Comment by jheiselman** [comment] 2021-09-01 18:54
As a point of clarification, does this commercial license offer support for just Redis Cluster or Redis Sentinel? They are two different things and we are running Sentinel for our Redis HA solution, not Cluster.

**Comment by zandbelt** [comment] 2021-09-01 19:23
Just cluster support so far, no sentinel

**Comment by jheiselman** [comment] 2021-09-01 19:27
@zandbelt if that changes, please post an update. We are looking at changing IAM products soon and shared session cache is a hard requirement. So far, this is the only thing holding us back from using mod_auth_openidc and we are willing to pay for commercial support.

**Comment by zandbelt** [comment] 2021-09-08 19:02
There's WIP on Redis Sentinel support under a commercial license in the same way as done with Redis Cluster/TLS before. If you are interested, please contact sales@zmartzone.eu

**Closed by zandbelt** 2021-09-08 19:02 UTC
Labels: enhancement
