### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on brave browser during authentication

### ISSUE THREAD

**Issue by drkancharla** [zmartzone/mod_auth_openidc#452] opened 2019-10-16 19:56 UTC
"This issue is specific to Brave browser"

From the module logs, it indicates that the state calculated from the cookie doesn't match the state that was sent back from authentication. Logs:
```
[Mon Oct 07 21:19:47.140316 2019] [auth_openidc:error] [pid 30149:tid 139668068849408] [client 100.72.88.81:58274] oidc_restore_proto_state: calculated state from cookie does not match state parameter passed back in URL: "AHpWUBkxG2C4fqC0TVOAOtoBXjw" != "HoA-dpJ6RJZ4F2hFlRRgSXrzVw0"

[Mon Oct 07 21:19:47.140344 2019] [auth_openidc:error] [pid 30149:tid 139668068849408] [client 100.72.88.81:58274] oidc_authorization_response_match_state: unable to restore state
```

Upon further digging, it seems that Brave browser introduced a new feature to enhance privacy and have started changing the user-agent between the calls from the same session.
For instance, user-agent in first request: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Brave Brave Brave Brave Brave Brave Brave Brave Brave Chrome/77.0.3865.90 Safari/537.36"
user-agent in second request: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Brave Brave Brave Brave Brave Brave Brave Chrome/77.0.3865.90 Safari/537.36"  

And this behavior is causing downstream issues in the module thereby resulting in an indefinite authentication loop.

Given that user-agent is commonly used for many purposes there is a chance that this feature might be rolled back in brave browser. However, there is also a chance that it can be picked up by other browsers in which this will be a bigger issue. Logging this request here for tracking purposes.

**Comment by zandbelt** [comment] 2019-10-17 07:16
My take on this:

I'm not inclined to make a change for it because I think there is more stuff out there that will break and the purpose of the User-Agent header does not allow changing its value randomly.
Therefore I think this behaviour will be fixed in the browser in due time.

On the other hand: the change is only small. But it would reduce security a bit to remove it, hence I'll wait to see what the demand for it is.

Others: please provide opinions/comments/support in this issue.

**Comment by fmarier** [comment] 2019-10-18 21:18
That looks like a bug in Brave.

Are you able to provide us with reproduction steps and/or [file a bug](https://github.com/brave/brave-browser/issues/new) so that we can investigate and hopefully fix on our end?

**Comment by zandbelt** [comment] 2019-10-23 16:18
I am going to close here since I really believe it should and will be fixed in the browser.

**Closed by zandbelt** 2019-10-23 16:18 UTC
Labels: enhancement, question

**Comment by fmarier** [comment] 2019-10-23 16:43
> I am going to close here since I really believe it should and will be fixed in the browser.

Was a bug filed upstream? I don't see anything if I search for "ERR_TOO_MANY_REDIRECTS", "mod_auth_openidc" or "openid" on https://github.com/brave/brave-browser/issues.

**Comment by mikegrima** [comment] 2019-11-16 18:51
I filed the issue upstream: https://github.com/brave/brave-browser/issues/6966
