### ISSUE TITLE
oidc_clean_expired_state_cookies : state has expired

### ISSUE THREAD

**Issue by alexandrehoarau** [zmartzone/mod_auth_openidc#315] opened 2017-12-04 07:14 UTC
Hi Everybody,
I encounter an issue with opendic module with apache2.
It seems the cookie has expired. Could you please help me ?
Please find below more information.
Regards,
Alexandre

Log output : 

[Thu Nov 30 14:15:18.653205 2017] [auth_openidc:error] [pid 8473] [client Address_IP:48196] oidc_clean_expired_state_cookies: state (mod_auth_openidc_state_uH4bMmVqEd1LOmVYT9ESOXpR6pU) has expired

Behaviour :
In fact, I configured apache2  to handle Request Tracker requests in order to redirect them to our OpenID Connect provider.
So, when I'm redirecting to the OpenID Provider, I'm not able to authenticate or enter my credentials due to this issue.

###### Environment

- mod_auth_openidc version : 2.3.2
- Apache version :  2.4.23 
- platform/distro : Suse

###### Apache Configuration  

    <VirtualHost *:443>
       OIDCProviderIssuer https://***********************/oauth2
       OIDCProviderAuthorizationEndpoint https://**********************/oauth2-as/oauth2-authz
       OIDCProviderTokenEndpoint https://**********************/oauth2/tokeninfo
       #OIDCProviderTokenEndpoint https://**********************/oauth2/token
       OIDCProviderUserInfoEndpoint https://**********************/oauth2/userinfo
       OIDCProviderTokenEndpointAuth client_secret_basic
       OIDCClientID **********************
       OIDCClientSecret *********************
       OIDCProviderAuthRequestMethod GET
       OIDCRedirectURI https://**********************/openidc
       OIDCCryptoPassphrase qAzAMLzAPA
       OIDCSSLValidateServer Off
       OIDCScope "openid email"
       OIDCRemoteUserClaim preferred_username

    <Location />
   	AuthType openid-connect
   	Require valid-user

         SetHandler modperl // Handle Request Tracker Request
         PerlResponseHandler Plack::Handler::Apache2
         PerlSetVar psgi_app /opt/rt4/sbin/rt-server
    </Location>
   
    <LocationMatch "/NoAuth">
    	Require all granted     
    </LocationMatch>
    <Perl>
        use Plack::Handler::Apache2;   // Handle Request Tracker Request
        Plack::Handler::Apache2->preload("/opt/rt4/sbin/rt-server");
    </Perl>
</VirtualHost>

**Comment by zandbelt** [comment] 2017-12-04 09:12
The error in `oidc_clean_expired_state_cookies` means that you had some sort of loop that piles up state cookies. You should check your application and server log and prevent the loop or parallel requests.

**Comment by zandbelt** [comment] 2017-12-12 11:39
any luck with that?

**Comment by alexandrehoarau** [comment] 2017-12-12 11:42
Hi Hans,

Unfortunately not, I'm looking for the missing parameter on the server side, but cannot find it because it works with some other python / any plugins with our OIDC provider.

Cheers,
Alex

**Comment by zandbelt** [comment] 2017-12-12 11:47
`LogLevel debug` should tell more

**Comment by zandbelt** [comment] 2018-01-10 07:57
@alexandrehoarau did you make any progress with the debug logs?

**Comment by alexandrehoarau** [comment] 2018-01-11 14:47
Hi Hans,

Thanks for the follow up, but unfortunately not. If you have hints/tips please let me know

Alexandre

**Comment by zandbelt** [comment] 2018-01-15 13:56
If you can start with a clean browser (all cookies removed), reproduced the problem and send the server logs & browser traces perhaps we can find out more. In anticipation of that I'll close this assuming it is a configuration issue.

**Closed by zandbelt** 2018-01-15 13:56 UTC

**Comment by zandbelt** [comment] 2018-01-17 17:44
OIDCProviderJwksUri needed to be set as was apparent from the logs

**Comment by 25bobby** [comment] 2022-03-11 21:54
Hi, I am new to the `mod_auth_openidc`. I am facing the same issue, 
```
[Fri Mar 11 21:35:13.742643 2022] [auth_openidc:error] [pid 12:tid 281473298985376] [client 192.168.144.1:62410] oidc_clean_expired_state_cookies: state (mod_auth_openidc_state_JLMQANO0xmYRv6uv31wZ4BEiJu0) has expired
```

I running the ubuntu:18.04 in a docker container and use `libapache2-mod-auth-openidc_2.3.3-1build1_arm64` build on a arm64 platform but it doesn't seem to be an issue when using the `libapache2-mod-auth-openidc_2.3.3-1.jessie.1_amd64` on an amd64 platform. 

Not sure what is the reason but can you provide help on how to set the OIDCProviderJwksUri? Thanks.

**Comment by zandbelt** [comment] 2022-03-13 12:24
This error is different and is harmless assuming it occurs rarely.

**Comment by ossdhaval** [comment] 2022-04-28 11:03
Cleaning browser cookies worked for me :+1:

**Comment by faizanshah512** [comment] 2022-06-14 15:18
hi i am facing the same error oidc_clean_expired_state_cookies: state (mod_auth_openidc_state_N47tBiKRsk0rH3zcJwfRGe2hq5U) has expired, referer: https://iam-front.test.com/login

**Comment by arLevi** [comment] 2023-02-13 12:13
I added to my configuration:
```OIDCSessionMaxDuration 84600``` if it helps someone ...
